version: '3'

services:
  frontend: 
    container_name: frontend
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
#   env_file:
#       - .env.backend.local
#volumes:
# node_modules:
